In [21]:
import re
import os
import time
import random
import requests
import gensim
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from os import system
from math import floor
from copy import deepcopy
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from nltk.stem import WordNetLemmatizer
from gensim.parsing.preprocessing import STOPWORDS

In [ ]:
conda forge install

In [5]:
%matplotlib inline
from mpl_toolkits.basemap import Basemap

KeyError: 'PROJ_LIB'

In [22]:
towny=pd.read_csv('towny_w_locs',index_col=0)

In [23]:
us_state_abbrev = {
    'Alabama': 'AL',    'Alaska': 'AK',    'Arizona': 'AZ',    'Arkansas': 'AR',    'California': 'CA',    'Colorado': 'CO',    'Connecticut': 'CT',    'Delaware': 'DE',    'District of Columbia': 'DC',    'Florida': 'FL',    'Georgia': 'GA',    'Hawaii': 'HI',    'Idaho': 'ID',    'Illinois': 'IL',    'Indiana': 'IN',    'Iowa': 'IA',    'Kansas': 'KS',    'Kentucky': 'KY',    'Louisiana': 'LA',    'Maine': 'ME',    'Maryland': 'MD',    'Massachusetts': 'MA',    'Michigan': 'MI',    'Minnesota': 'MN',    'Mississippi': 'MS',    'Missouri': 'MO',    'Montana': 'MT',    'Nebraska': 'NE',    'Nevada': 'NV',    'New Hampshire': 'NH',    'New Jersey': 'NJ',    'New Mexico': 'NM',    'New York': 'NY',    'North Carolina': 'NC',    'North Dakota': 'ND',    'Northern Mariana Islands':'MP',    'Ohio': 'OH',    'Oklahoma': 'OK',    'Oregon': 'OR',    'Palau': 'PW',    'Pennsylvania': 'PA',    'Puerto Rico': 'PR',    'Rhode Island': 'RI',    'South Carolina': 'SC',    'South Dakota': 'SD',    'Tennessee': 'TN',    'Texas': 'TX',    'Utah': 'UT',    'Vermont': 'VT',    'Virgin Islands': 'VI',    'Virginia': 'VA',    'Washington': 'WA',    'West Virginia': 'WV',    'Wisconsin': 'WI',    'Wyoming': 'WY',}
abr2full = dict([[v,k] for k,v in us_state_abbrev.items()])

In [234]:
def get_loc_from_wiki(name):
    enter_text=driver.find_element_by_xpath('//*[@id="searchInput"]')
    enter_text.clear()
#     print('just_cleared')
    enter_text.send_keys(name)
#     print('sent '+name)
#     time.sleep(.1)
#     print('click')
    driver.find_element_by_xpath('//*[@id="searchButton"]').click()
    time.sleep(.5)
    try:
        driver.find_element_by_xpath('//*[@id="mw-content-text"]/div[3]/p[1]/i')
        driver.find_element_by_xpath('//*[@id="mw-content-text"]/div[3]/ul/li[1]/div[1]/a').click()
    except:
        print('straight to page')
    try:
        driver.find_element_by_xpath('//*[@id="coordinates"]/a')

    except:
        time.sleep(.5)
        try:
            driver.find_element_by_xpath('//*[@id="mw-content-text"]/div/ul[1]/li[1]/a').click()
        except:
            try:
                driver.find_element_by_xpath('//*[@id="mw-content-text"]/div[4]/ul/li[1]/div[1]/a').click()
            except:
                print('lmaooooo')
                try:
                    lat=driver.find_element_by_class_name('latitude').text
                    lon=driver.find_element_by_class_name('longitude').text
            #         ('document.querySelector("#mw-content-text > div > table.infobox.geography.vcard > tbody > tr.mergedbottomrow > td > span > span > a > span.geo-default > span > span.latitude")')
            #         ('<span class="latitude">46°48′48″N</span>')
            #         lon=driver.find_element_by_css_selector('#mw-content-text > div > table.infobox.geography.vcard > tbody > tr.mergedbottomrow > td > span.plainlinks.nourlexpansion > span > a > span.geo-default > span > span.longitude').text
                    latlon=lat+' '+lon
                    if latlon==' ':
                        latlon=driver.find_element_by_class_name('geo-dec').text
                except:
            
                    latlon=''
                return latlon
#                 return get_loc_from_wiki(name)
    time.sleep(.1)
    try:
        lat=driver.find_element_by_class_name('latitude').text
        lon=driver.find_element_by_class_name('longitude').text
#         ('document.querySelector("#mw-content-text > div > table.infobox.geography.vcard > tbody > tr.mergedbottomrow > td > span > span > a > span.geo-default > span > span.latitude")')
#         ('<span class="latitude">46°48′48″N</span>')
#         lon=driver.find_element_by_css_selector('#mw-content-text > div > table.infobox.geography.vcard > tbody > tr.mergedbottomrow > td > span.plainlinks.nourlexpansion > span > a > span.geo-default > span > span.longitude').text
        latlon=lat+' '+lon
        if latlon==' ':
            latlon=driver.find_element_by_class_name('geo-dec').text
    except:

        latlon=''
    return latlon

In [151]:
driver.find_element_by_xpath('//*[@id="mw-content-text"]/div[3]/ul/li[1]/div[1]/a').click()

In [35]:
driver.find_element_by_css_selector('#mw-content-text > div > table.infobox.geography.vcard > tbody > tr.mergedbottomrow > td > span.plainlinks.nourlexpansion > span > a > span.geo-default > span > span.longitude').text

'91°23′15″W'

In [47]:
names=towny['town']
# names_=names.apply(lambda u: '_'.join(u.split(', ')))
names_=names.apply(lambda u: u.replace(' ',' ').replace(',',''))
names_.head()

0     Bismarck ND
1    Ridgewood NJ
2      Natchez MS
3    Southaven MS
4     Garfield NJ
Name: town, dtype: object

In [228]:
driver = webdriver.Chrome()

In [105]:
def full_name(abr_st):
    toon=abr_st.split()
    town=toon[:-1]
    state=toon[-1]
#     print(town)
#     print(abr2full[state])
    return'{} {}'.format(' '.join(town),abr2full[state])

In [15]:
print(full_name('Portland, ME'))

Portland, Maine

In [19]:
driver.get('https://en.wikipedia.org/wiki/Hanover_Park,_Illinois')

NameError: name 'driver' is not defined

In [242]:
# locations=[]
# num=1042
# locations=locations[:num]
for i,name in enumerate(names_[num:]):
    loc=get_loc_from_wiki(full_name(name))
#     loc=('lat','lon')
    print(f'{i+num}|{full_name(name)}: \n    lat & lon: {loc}')
    locations.append(loc)

straight to page
1042|Hudson New Hampshire:
    lat & lon: 42°33′20″N 114°28′15″W
1043|Bowie Maryland:
    lat & lon: 38°57′53″N 76°44′40″W
straight to page
1044|Hartford Connecticut:
    lat & lon: 41°45′45″N 72°40′27″W
1045|Hamilton Ohio:
    lat & lon: 39°23′58″N 84°33′41″W
1046|Matthews North Carolina:
    lat & lon: 35°7′1″N 80°42′59″W
1047|Grand Island Nebraska:
    lat & lon: 40°55′20″N 98°21′29″W
1048|Palm Coast Florida:
    lat & lon: 29°32′17″N 81°13′24″W
1049|Oklahoma City Oklahoma:
    lat & lon: 35°28′56″N 97°32′06″W
straight to page
1050|Evansville Indiana:
    lat & lon: 37°58′38″N 87°33′2″W
1051|Wausau Wisconsin:
    lat & lon: 44°57′N 89°38′W
1052|Dawsonville Georgia:
    lat & lon: 34°25′N 84°7′W
1053|Kokomo Indiana:
    lat & lon: 40°28′56″N 86°7′54″W
straight to page
1054|Honolulu Hawaii:
    lat & lon: 21°18′N 157°49′W
1055|Sheboygan Wisconsin:
    lat & lon: 43°45′0″N 87°43′30″W
1056|Piscataway New Jersey:
    lat & lon: 40.54564°N 74.460817°W
1057|Cocoa Florida:
    lat & lon: 28°22′10″N 80°44′38″W
1058|Cartersville Georgia:
    lat & lon: 34°11′N 84°48′W
1059|Chatsworth Georgia:
    lat & lon: 34°46′20″N 84°46′44″W
straight to page
1060|Grandville Michigan:
    lat & lon: 42°54′14″N 85°45′27″W
1061|New Britain Connecticut:
    lat & lon: 41°40′30″N 72°47′14″W
1062|Northville Michigan:
    lat & lon: 42°26′00″N 83°29′00″W
1063|Waltham Massachusetts:
    lat & lon: 42°22′20″N 71°12′41″W
1064|Butler Pennsylvania:
    lat & lon: 40°51′38″N 79°53′41″W

In [253]:
# locations=[]
# num=1042
# locations=locations[:num]
fixed=[]
for i in fix:
    loc=get_loc_from_wiki(full_name(names_[i]))
#     loc=('lat','lon')
    print(f'{i+num}|{full_name(names_[i])}: \n    lat & lon: {loc}')
    fixed.append(loc)

483|Copperas Cove Texas:
    lat & lon: 31°7′11″N 97°54′6″W
669|Hamtramck Michigan:
    lat & lon: 42°23′52″N 83°03′26″W
lmaooooo
761|Hephzibah Georgia:
    lat & lon: 33°18′15″N 82°5′53″W
848|Grove City Ohio:
    lat & lon: 39°52′41″N 83°4′41″W
892|Whitehall Pennsylvania:
    lat & lon:
893|Hackensack New Jersey:
    lat & lon: 40.889398°N 74.045698°W

In [256]:
fixed

['31°7′11″N 97°54′6″W',
 '42°23′52″N 83°03′26″W',
 '33°18′15″N 82°5′53″W',
 '39°52′41″N 83°4′41″W',
 '40°21′37″N 79°59′11″W',
 '40.889398°N 74.045698°W']

In [255]:
fixed[4]=latlon

In [187]:
locations=locations[:295]

In [214]:
locations.append('')

In [197]:
names_[297]

'Wallingford CT'

In [254]:
lat=driver.find_element_by_class_name('latitude').text
lon=driver.find_element_by_class_name('longitude').text
#         ('document.querySelector("#mw-content-text > div > table.infobox.geography.vcard > tbody > tr.mergedbottomrow > td > span > span > a > span.geo-default > span > span.latitude")')
#         ('<span class="latitude">46°48′48″N</span>')
#         lon=driver.find_element_by_css_selector('#mw-content-text > div > table.infobox.geography.vcard > tbody > tr.mergedbottomrow > td > span.plainlinks.nourlexpansion > span > a > span.geo-default > span > span.longitude').text
latlon=lat+' '+lon

In [249]:
fix=[]
for k,num in enumerate([len(i) for i in locations]):
    if num<3:
        fix.append(k)

In [259]:
for i,num in zip(fixed,fix):
    locations[num]=i
    print(locations[num])

31°7′11″N 97°54′6″W
42°23′52″N 83°03′26″W
33°18′15″N 82°5′53″W
39°52′41″N 83°4′41″W
40°21′37″N 79°59′11″W
40.889398°N 74.045698°W

In [258]:
back=locations

In [266]:
# lat=[k.split()[0] for k in locations]
# towny['lat']=lat
lon=[k.split()[1] for k in locations]
towny['lon']=lon

In [263]:
towny['lat']=lat

In [314]:
import re

def dms2dec(dms_str):
    """Return decimal representation of DMS
    
    >>> dms2dec(utf8(48°53'10.18"N))
    48.8866111111F
    
    >>> dms2dec(utf8(2°20'35.09"E))
    2.34330555556F
    
    >>> dms2dec(utf8(48°53'10.18"S))
    -48.8866111111F
    
    >>> dms2dec(utf8(2°20'35.09"W))
    -2.34330555556F
    
    """
    
    dms_str = re.sub(r'\s', '', dms_str)
    
    sign = -1 if re.search('[swSW]', dms_str) else 1
    
    numbers = list(filter(len, re.split('\D+', dms_str, maxsplit=4)))
#     print(numbers)
    degree = numbers[0]
    minute = numbers[1] if len(numbers) >= 2 else '0'
    second = numbers[2] if len(numbers) >= 3 else '0'
    frac_seconds = numbers[3] if len(numbers) >= 4 else '0'
    
    second += "." + frac_seconds
    return sign * (int(degree) + float(minute) / 60 + float(second) / 3600)

In [8]:
towny.lat.map(dms2dec)

NameError: name 'towny' is not defined

In [295]:
# num=1
# print('town: {}\nlatlon: {} {}'.format(towny.iloc[num]['town'],dms2dec(towny.lat[num]),dms2dec(towny.lon[num])))
num=1
print('town: {}\nlatlon: {} {}'.format(towny.iloc[num]['town'],towny.lat[num],towny.lon[num]))

town: Ridgewood, NJ
latlon: 40.981591°N 74.113506°W

In [18]:
towny.head(2)

,town,biz,com_elec_ghg,com_gas_1kdol,com_gas_ghg,com_gas_mcf,houses,ind,ind_elec_ghg,ind_gas_1kdol,...,res_gas_ghg,res_gas_mcf,age,edu,income,poverty,lat,lon,convlat,convlon
0,"Bismarck, ND",927.0,337550656.0,4000.0,88869152.0,740313.0,29680.0,290.0,262308579.0,2668.0,...,188394738.0,1569398.0,37.1,93.1,61477,9.5,46°48′48″N,100°46′44″W,46.813333,-100.778889
1,"Ridgewood, NJ",653.0,202329017.0,2790.0,46272451.0,385467.0,8335.0,88.0,4662251.0,133.0,...,121772514.0,1014410.0,41.3,97.1,162011,4.4,40.981591°N,74.113506°W,40.981591,74.113506

In [14]:
conv=[]
for i,row in towny.iterrows():
    num=i
    if towny.lat[num][2]=='.':
        print(i)
#         print('town: {}\nlatlon: {} {}'.format(towny.iloc[num]['town'],towny.lat[num],towny.lon[num]))

        print(towny)
    else:
        conv.append(0)
#         print('na')

1
4
16
48
49
50
65
66
69
77
107
110
116
124
125
139
156
157
167
170
177
196
198
236
252
255
257
260
277
291
294
308
324
336
339
343
375
400
409
418
445
446
454
464
465
499
505
507
514
517
523
561
564
578
580
586
591
625
644
647
660
677
683
684
685
691
694
701
702
732
745
768
769
791
794
800
808
825
828
830
834
857
861
866
867
872
876
882
890
891
892
910
912
918
940
955
958
961
962
963
986
987
993
997
1019
1032
1040
1056

In [312]:
len(conv)

1065

In [332]:
convlat=[]
for i, row in towny.iterrows():
    num=i
    if row.lat[2]=='.':
#         print(i)
#         print('town: {}\nlatlon: {} {}'.format(towny.iloc[num]['town'],towny.lat[num],towny.lon[num]))
        convlat.append(float(row.lat.split('°')[0]))
    else:
        convlat.append(dms2dec(row.lat))
convlon=[]
for i, row in towny.iterrows():
    num=i
    if row.lon[2]=='.':
#         print(i)
#         print('town: {}\nlatlon: {} {}'.format(towny.iloc[num]['town'],towny.lat[num],towny.lon[num]))
        convlon.append(float(row.lon.split('°')[0]))
    else:
        convlon.append(dms2dec(row.lon))

In [324]:
convlon

[46.81333333333333,
 40.981591,
 31.554444444444446,
 34.96666666666667,
 40.879797,
 41.312777777777775,
 35.654444444444444,
 41.305277777777775,
 28.540000000000003,
 42.58222222222223,
 29.99277777777778,
 41.896388888888886,
 41.888333333333335,
 46.203611111111115,
 34.93805555555555,
 48.23305555555556,
 35.22,
 39.26888888888889,
 39.89222222222222,
 40.75361111111111,
 42.4175,
 40.87972222222222,
 41.373333333333335,
 36.85472222222222,
 33.52444444444444,
 28.693333333333335,
 34.51444444444444,
 40.79666666666667,
 41.87583333333333,
 39.94138888888889,
 39.80722222222222,
 35.8775,
 42.11694444444444,
 42.284166666666664,
 45.117222222222225,
 41.68111111111111,
 35.60166666666667,
 43.051944444444445,
 41.87111111111111,
 32.45916666666667,
 35.93833333333333,
 34.96027777777778,
 41.543055555555554,
 41.04277777777778,
 42.03472222222222,
 40.37166666666667,
 44.733333333333334,
 42.266666666666666,
 40.486678,
 39.842012,
 40.820568,
 37.88055555555555,
 38.88194444444444,
 34.36944444444445,
 47.0425,
 43.094722222222224,
 42.37027777777778,
 34.02194444444444,
 36.03333333333333,
 41.38944444444444,
 37.07083333333334,
 41.3925,
 41.1,
 41.30416666666667,
 45.18888888888888,
 40.732672,
 40.95,
 34.140277777777776,
 36.68611111111111,
 40.092566,
 30.411944444444444,
 41.17055555555555,
 41.40222222222222,
 41.830000000000005,
 29.599444444444444,
 39.83361111111111,
 42.39722222222222,
 39.39,
 44.52305555555555,
 37.552499999999995,
 47.42333333333333,
 41.76138888888889,
 38.80472222222222,
 39.57666666666667,
 28.65972222222222,
 43.14861111111111,
 41.66111111111111,
 34.98166666666667,
 36.06444444444444,
 40.44194444444444,
 39.1,
 42.797777777777775,
 35.791666666666664,
 34.11694444444444,
 41.48222222222223,
 40.513888888888886,
 42.28138888888889,
 42.92722222222222,
 40.68833333333333,
 40.261944444444445,
 38.29555555555555,
 43.41777777777777,
 40.265277777777776,
 42.49805555555556,
 42.88055555555555,
 34.05277777777778,
 42.73361111111111,
 40.824415,
 42.065555555555555,
 42.666666666666664,
 42.5,
 41.88194444444444,
 40.80916666666666,
 41.415,
 40.913333333333334,
 31.22722222222222,
 41.7,
 42.90472222222222,
 43.178888888888885,
 27.1,
 34.25972222222222,
 42.12111111111111,
 42.06305555555555,
 26.709722222222222,
 40.63,
 40.890317,
 39.469722222222224,
 41.323888888888895,
 36.75,
 41.52055555555555,
 41.446666666666665,
 33.871944444444445,
 38.365833333333335,
 40.2025,
 41.6675,
 33.71277777777778,
 27.192222222222224,
 28.560277777777777,
 42.19444444444444,
 40.851,
 42.55833333333333,
 29.28638888888889,
 35.7425,
 34.1,
 41.385,
 42.50833333333333,
 32.96555555555556,
 42.22638888888889,
 36.58722222222222,
 47.92527777777777,
 39.99777777777778,
 43.06666666666667,
 33.93333333333333,
 35.913888888888884,
 39.26611111111111,
 33.44499999999999,
 40.891197,
 40.357115,
 27.997922222222222,
 45.144999999999996,
 42.615833333333335,
 32.786944444444444,
 28.66111111111111,
 40.12,
 26.234722222222224,
 40.626111111111115,
 42.348333333333336,
 40.02795,
 32.75,
 37.815555555555555,
 43.42,
 28.066944444444445,
 33.534166666666664,
 31.8325,
 35.04555555555555,
 41.15861111111111,
 44.82777777777778,
 40.497692,
 41.09388888888889,
 35.88583333333333,
 34.195277777777775,
 35.580000000000005,
 44.8,
 37.24388888888889,
 38.301944444444445,
 34.62722222222222,
 42.78333333333333,
 41.744166666666665,
 40.489444444444445,
 38.85944444444445,
 30.433333333333334,
 33.00805555555556,
 43.57472222222223,
 42.24166666666667,
 42.391666666666666,
 30.669444444444444,
 40.922334,
 40.86,
 40.76746,
 41.980555555555554,
 30.455,
 44.290588888888884,
 33.749722222222225,
 34.062777777777775,
 40.15472222222222,
 41.63638888888889,
 34.02333333333333,
 42.20527777777778,
 41.01305555555555,
 41.48972222222222,
 41.693888888888885,
 42.35805555555556,
 29.416666666666668,
 36.98166666666667,
 41.55611111111111,
 37.38944444444444,
 42.90555555555555,
 44.21666666666667,
 35.36666666666667,
 39.599722222222226,
 40.175,
 32.69222222222222,
 40.19333333333333,
 42.038333333333334,
 33.65333333333333,
 42.7575,
 40.22833333333333,
 33.58083333333334,
 42.415277777777774,
 33.0,
 42.86666666666667,
 42.243611111111115,
 37.333333333333336,
 41.766666666666666,
 41.61416666666667,
 42.4925,
 40.75,
 39.481388888888894,
 44.08722222222222,
 42.19222222222222,
 40.615,
 33.03666666666666,
 40.95888888888889,
 37.28388888888889,
 47.12111111111111,
 33.19361111111111,
 41.05277777777778,
 42.20416666666667,
 36.333333333333336,
 30.16861111111111,
 40.249722222222225,
 38.81638888888889,
 43.05,
 42.865,
 26.349722222222223,
 40.856413,
 42.32416666666667,
 39.848539,
 44.09638888888889,
 44.981944444444444,
 39.427518,
 46.35805555555556,
 33.23111111111111,
 42.961111111111116,
 44.166666666666664,
 40.75888888888889,
 43.53638888888889,
 33.771388888888886,
 42.61055555555556,
 36.32694444444445,
 36.32694444444445,
 34.75972222222222,
 33.51305555555555,
 29.792222222222225,
 44.64972222222222,
 35.1175,
 41.25,
 40.223748,
 40.98583333333333,
 40.177499999999995,
 34.82333333333334,
 35.89388888888889,
 42.41833333333333,
 26.318055555555556,
 30.42027777777778,
 42.68111111111111,
 41.71416666666667,
 43.45472222222222,
 42.425,
 43.18360277777777,
 33.836111111111116,
 40.656391,
 34.05138888888889,
 34.946666666666665,
 39.803179,
 39.68472222222222,
 47.91916666666666,
 41.45638888888889,
 35.970555555555556,
 33.37638888888889,
 40.11277777777778,
 40.79138888888889,
 33.3675,
 42.50472222222222,
 42.525555555555556,
 41.48555555555556,
 42.240833333333335,
 41.71138888888889,
 40.76746,
 36.01555555555556,
 26.639722222222222,
 47.821111111111115,
 40.70472222222222,
 28.701944444444443,
 26.616666666666667,
 43.35944444444445,
 40.20416666666667,
 42.46472222222223,
 42.766666666666666,
 41.575,
 35.846111111111114,
 41.38333333333333,
 33.805277777777775,
 43.59505,
 41.492,
 41.876111111111115,
 41.93333333333333,
 33.85805555555556,
 28.041111111111114,
 34.5,
 41.92027777777778,
 43.20888888888889,
 44.513333333333335,
 40.67022222222222,
 39.08361111111111,
 42.50333333333333,
 39.423563,
 42.44333333333333,
 33.731944444444444,
 40.450387,
 32.27194444444444,
 35.11222222222222,
 42.698611111111106,
 42.558,
 43.21944444444445,
 41.27777777777778,
 39.76305555555555,
 43.12222222222222,
 33.5625,
 36.52972222222222,
 35.47888888888889,
 41.22777777777778,
 30.846666666666664,
 39.9375,
 40.24111111111111,
 44.051944444444445,
 43.04111111111111,
 41.931666666666665,
 35.19916666666666,
 26.15,
 43.01166666666666,
 32.361666666666665,
 41.63611111111111,
 40.29888888888889,
 39.841944444444444,
 41.165277777777774,
 39.28333333333333,
 26.0125,
 25.813025,
 39.96,
 42.31444444444444,
 42.467222222222226,
 44.28333333333333,
 42.125,
 33.88666666666666,
 40.296142,
 44.44611111111111,
 41.27388888888889,
 33.39899166666667,
 39.28333333333333,
 41.42388888888889,
 42.68388888888889,
 38.93333333333333,
 42.16166666666666,
 33.53861111111111,
 39.84722222222222,
 28.24888888888889,
 33.865833333333335,
 37.96222222222222,
 41.501666666666665,
 41.55027777777777,
 41.88861111111111,
 35.07694444444445,
 26.926111111111112,
 40.155,
 42.24277777777778,
 40.94138888888889,
 27.522222222222222,
 27.522222222222222,
 41.02777777777778,
 40.615444,
 43.06027777777778,
 41.11694444444444,
 34.05,
 34.359722222222224,
 42.40833333333333,
 33.931666666666665,
 30.63111111111111,
 42.57916666666667,
 40.765058,
 28.676111111111112,
 42.095,
 33.08777777777778,
 38.97138888888889,
 44.71333333333334,
 42.16833333333333,
 40.18083333333333,
 39.01361111111111,
 40.574413,
 33.6,
 28.661388888888887,
 25.471188888888886,
 42.03388888888889,
 39.13472222222222,
 39.81666666666667,
 26.133333333333333,
 39.64277777777778,
 38.55555555555555,
 28.7575,
 28.7575,
 33.744075,
 42.506388888888885,
 27.973611111111108,
 41.691111111111105,
 36.080000000000005,
 42.49194444444444,
 34.086111111111116,
 40.21222222222222,
 44.266666666666666,
 32.907222222222224,
 34.77111111111111,
 41.6075,
 35.410555555555554,
 44.097500000000004,
 34.04888888888889,
 40.853704,
 40.853704,
 41.85277777777778,
 41.93138888888889,
 42.07611111111112,
 35.244166666666665,
 45.78333333333333,
 41.55027777777777,
 41.9,
 40.895786,
 41.605000000000004,
 41.605000000000004,
 29.11888888888889,
 41.70944444444445,
 41.70944444444445,
 41.29555555555555,
 41.51972222222222,
 31.119722222222222,
 33.888888888888886,
 40.794175,
 41.15,
 28.574166666666667,
 42.02055555555555,
 39.077222222222225,
 42.63944444444444,
 35.766666666666666,
 31.149722222222223,
 40.72083333333334,
 34.970555555555556,
 34.970555555555556,
 30.516111111111112,
 26.619722222222222,
 34.19138888888889,
 34.730000000000004,
 38.956944444444446,
 35.6225,
 41.66555555555556,
 42.652499999999996,
 43.01888888888889,
 42.25,
 40.01111111111111,
 39.16222222222222,
 40.1475,
 40.1475,
 40.24194444444444,
 38.03,
 42.030277777777776,
 35.336666666666666,
 28.173333333333336,
 42.46666666666667,
 42.93333333333333,
 41.123333333333335,
 41.698611111111106,
 35.38194444444444,
 40.795515,
 33.755,
 42.90123611111111,
 42.07944444444445,
 42.33916666666667,
 42.98027777777778,
 40.51,
 30.988480555555558,
 40.72386,
 41.583333333333336,
 28.111666666666668,
 28.111666666666668,
 35.973333333333336,
 39.95277777777778,
 28.59611111111111,
 41.534414,
 40.03444444444444,
 28.496666666666666,
 40.788888,
 42.16277777777778,
 32.90694444444444,
 33.987500000000004,
 33.2475,
 42.22222222222222,
 40.077041,
 33.370555555555555,
 35.64722222222222,
 43.61555555555556,
 41.25,
 24.559722222222224,
 41.159444444444446,
 42.04055555555556,
 28.929166666666667,
 42.458333333333336,
 35.91313888888889,
 35.91313888888889,
 44.695277777777775,
 34.91722222222222,
 47.50361111111111,
 32.5375,
 43.16972222222222,
 41.42166666666667,
 42.50666666666667,
 42.50666666666667,
 37.21277777777778,
 40.05,
 30.52638888888889,
 37.495555555555555,
 39.316944444444445,
 39.316944444444445,
 34.95861111111111,
 42.395833333333336,
 41.60416666666667,
 40.440555555555555,
 39.33638888888889,
 42.046388888888885,
 42.46611111111111,
 37.757777777777775,
 39.13194444444444,
 37.290277777777774,
 26.21638888888889,
 39.099722222222226,
 40.508651,
 42.271388888888886,
 39.11666666666667,
 40.593138,
 41.309999999999995,
 27.483333333333334,
 32.016666666666666,
 39.95611111111111,
 33.42222222222222,
 40.74,
 36.33638888888889,
 33.926944444444445,
 41.61083333333333,
 32.78333333333333,
 41.38166666666667,
 42.00833333333333,
 36.53333333333333,
 40.61,
 43.058055555555555,
 40.404632,
 33.21361111111111,
 33.45,
 28.59111111111111,
 41.82666666666667,
 41.72277777777778,
 39.99,
 41.82361111111111,
 31.759166666666665,
 38.75138888888889,
 35.749722222222225,
 40.75,
 39.35805555555556,
 39.35805555555556,
 42.519444444444446,
 27.909444444444443,
 48.19777777777777,
 26.459166666666665,
 42.16638888888889,
 42.814166666666665,
 41.97888888888889,
 25.93027777777778,
 47.609722222222224,
 27.74277777777778,
 41.83222222222223,
 40.568333333333335,
 40.568333333333335,
 45.05,
 37.14111111111111,
 30.401666666666664,
 41.72666666666667,
 40.18555555555555,
 42.57972222222222,
 41.17583333333333,
 36.07138888888889,
 35.171388888888885,
 32.834722222222226,
 41.65,
 33.30444444444444,
 45.31722222222223,
 39.98361111111111,
 31.315833333333334,
 41.186388888888885,
 39.53666666666666,
 41.85611111111111,
 39.465007,
 41.073055555555555,
 34.10138888888889,
 41.715,
 39.91888888888889,
 39.91888888888889,
 44.81666666666667,
 35.78666666666666,
 46.87166666666667,
 46.87166666666667,
 42.990833333333335,
 40.588055555555556,
 41.67638888888889,
 43.63166666666667,
 41.99527777777778,
 42.15361111111111,
 25.775277777777777,
 28.24888888888889,
 33.95305555555556,
 40.426247,
 39.61,
 39.903055555555554,
 41.3485,
 42.397777777777776,
 36.11611111111111,
 41.24444444444445,
 30.284166666666668,
 30.284166666666668,
 42.095555555555556,
 41.47675,
 32.715,
 42.20861111111111,
 42.726111111111116,
 34.733333333333334,
 41.68694444444444,
 40.785243,
 36.45444444444445,
 44.78333333333333,
 33.91861111111111,
 34.92833333333333,
 37.270833333333336,
 37.000277777777775,
 36.025277777777774,
 40.867222222222225,
 39.37111111111111,
 36.01027777777778,
 41.23305555555556,
 41.13583333333333,
 39.96277777777778,
 35.98861111111111,
 42.003055555555555,
 40.41722222222222,
 39.995351,
 41.71666666666667,
 44.930769444444444,
 42.47972222222222,
 42.03333333333333,
 37.34777777777778,
 39.94,
 40.691974,
 40.691974,
 37.778055555555554,
 30.21472222222222,
 42.083333333333336,
 41.8425,
 40.07027777777778,
 40.52016,
 39.94611111111111,
 42.32972222222222,
 40.989032,
 35.731944444444444,
 25.860555555555557,
 35.48888888888889,
 25.942122222222224,
 39.95861111111111,
 40.439722222222215,
 40.796562,
 42.5043,
 42.1625,
 42.1625,
 35.73105555555556,
 41.8,
 43.766666666666666,
 44.80305555555555,
 37.35444444444445,
 42.73166666666667,
 38.8,
 40.60166666666667,
 33.62166666666667,
 41.14555555555555,
 39.09583333333334,
 41.348888888888894,
 46.546388888888885,
 39.75944444444445,
 46.6,
 41.96666666666667,
 42.27916666666667,
 43.88444444444444,
 44.666666666666664,
 41.55138888888889,
 39.95305555555556,
 39.95305555555556,
 42.99611111111111,
 42.65833333333333,
 35.58444444444444,
 35.58444444444444,
 32.59916666666667,
 41.668784,
 40.99722222222222,
 45.67777777777778,
 42.599722222222226,
 37.94888888888889,
 40.86694444444444,
 33.67944444444444,
 44.174166666666665,
 33.30416666666667,
 40.26972222222222,
 30.174444444444447,
 41.794444444444444,
 40.315,
 40.260219,
 46.87722222222222,
 40.80888888888889,
 42.706944444444446,
 43.20666666666667,
 37.03472222222222,
 42.40833333333333,
 41.98305555555556,
 29.022499999999997,
 41.080450000000006,
 42.18666666666666,
 42.33166666666667,
 36.29555555555555,
 40.86277777777778,
 42.46055555555556,
 41.958333333333336,
 34.227222222222224,
 40.297777777777775,
 32.60861111111111,
 35.683055555555555,
 34.715,
 34.18583333333333,
 39.63861111111111,
 40.5274,
 40.72,
 42.077222222222225,
 42.525,
 39.80777777777777,
 44.85472222222222,
 42.583333333333336,
 40.2075,
 41.60722222222223,
 40.284166666666664,
 41.53666666666666,
 44.93333333333333,
 33.95333333333333,
 39.958333333333336,
 34.206944444444446,
 41.45444444444445,
 39.374722222222225,
 46.59580555555556,
 35.052499999999995,
 38.973055555555554,
 34.930277777777775,
 34.06083333333333,
 45.46472222222223,
 40.914746,
 40.515816666666666,
 37.05833333333333,
 40.295372,
 42.45333333333333,
 41.925,
 41.57916666666667,
 42.295833333333334,
 37.83555555555556,
 44.076,
 36.09583333333334,
 44.02472222222222,
 33.66638888888889,
 45.516666666666666,
 33.83888888888889,
 44.38666666666666,
 34.97638888888889,
 43.1117,
 35.227222222222224,
 40.90861111111111,
 41.57055555555556,
 44.05,
 32.336111111111116,
 39.75361111111111,
 41.476111111111116,
 35.32055555555556,
 41.983333333333334,
 40.91416666666667,
 34.003055555555555,
 42.55,
 47.02638888888889,
 42.74444444444445,
 29.762777777777778,
 33.56472222222222,
 40.182051,
 41.85944444444445,
 39.878055555555555,
 41.508251,
 38.471944444444446,
 40.876235,
 41.625,
 28.116666666666667,
 34.07333333333334,
 39.592075,
 41.55,
 32.509166666666665,
 34.44027777777777,
 42.37361111111111,
 42.38333333333333,
 29.036944444444448,
 47.47361111111111,
 28.30388888888889,
 34.50083333333333,
 35.1085,
 39.413888888888884,
 42.88444444444444,
 38.44944444444444,
 36.29416666666666,
 34.83083333333334,
 41.28194444444444,
 36.35472222222222,
 39.9,
 34.736111111111114,
 41.92194444444444,
 41.511944444444445,
 38.88583333333333,
 39.66078,
 35.25527777777778,
 33.462500000000006,
 42.37888888888889,
 40.935833,
 39.82833333333333,
 40.43111111111111,
 31.442777777777778,
 44.74111111111111,
 41.052742,
 40.786032,
 43.08305555555556,
 40.03444444444444,
 40.61666666666667,
 40.36027777777778,
 40.889398,
 42.87083333333334,
 27.968055555555555,
 41.01583333333333,
 40.75372,
 41.79472222222222,
 42.03333333333333,
 33.2,
 38.971111111111114,
 40.23388888888889,
 40.411248,
 42.11666666666667,
 30.236666666666668,
 43.666666666666664,
 41.32222222222222,
 35.05444444444444,
 42.125,
 38.26694444444444,
 39.904611,
 40.809128,
 39.948992,
 43.23416666666667,
 46.87388888888889,
 42.29,
 42.90611111111111,
 34.02194444444444,
 33.858333333333334,
 45.59111111111111,
 26.02138888888889,
 35.81666666666667,
 28.904999999999998,
 37.53333333333333,
 43.08972222222222,
 42.12916666666667,
 42.575,
 38.2,
 27.33722222222222,
 33.20666666666667,
 40.945855,
 37.230000000000004,
 40.839244,
 41.87722222222222,
 40.32777777777778,
 40.34166666666667,
 43.1,
 32.848333333333336,
 40.061736,
 42.129444444444445,
 28.033333333333335,
 40.038888888888884,
 34.76361111111111,
 43.666666666666664,
 41.70138888888889,
 41.20444444444445,
 42.86638888888889,
 28.816944444444445,
 40.875,
 38.9,
 39.55555555555555,
 30.4475,
 36.38138888888889,
 42.25472222222222,
 32.212500000000006,
 31.3275,
 42.8125,
 36.971944444444446,
 42.97916666666667,
 37.6625,
 41.89,
 33.838055555555556,
 34.23638888888889,
 37.80444444444444,
 39.846111111111114,
 41.68722222222222,
 39.63361111111111,
 40.130833333333335,
 35.68666666666666,
 42.464444444444446,
 33.54944444444444,
 40.12361111111111,
 35.69833333333333,
 43.19472222222222,
 35.47361111111111,
 40.268457,
 45.19777777777777,
 42.45,
 35.9617,
 40.78333333333333,
 37.07222222222222,
 40.093077,
 26.848788,
 40.200211,
 47.24138888888889,
 41.57694444444445,
 36.16416666666667,
 28.025277777777777,
 35.71527777777778,
 37.40361111111111,
 43.03111111111111,
 45.374722222222225,
 40.115,
 26.2,
 27.782777777777778,
 40.21083333333333,
 42.25,
 61.21666666666667,
 42.28333333333333,
 39.79138888888889,
 42.14861111111111,
 36.71416666666667,
 38.403888888888886,
 42.47916666666667,
 42.91361111111111,
 42.36666666666667,
 29.95,
 40.222884,
 32.75138888888889,
 41.7,
 28.325,
 35.0475,
 42.48583333333333,
 40.666261,
 41.35111111111111,
 42.23111111111111,
 43.81333333333333,
 39.377297,
 42.8875,
 42.48888888888889,
 ...]

In [333]:
towny['convlat']=convlat
towny['convlon']=convlon

In [334]:
towny[['town','convlat','convlon']].loc

                        town    convlat     convlon
0               Bismarck, ND  46.813333 -100.778889
1              Ridgewood, NJ  40.981591   74.113506
2                Natchez, MS  31.554444  -91.387500
3              Southaven, MS  34.966667  -89.987222
4               Garfield, NJ  40.879797   74.108250
5           Strongsville, OH  41.312778  -81.831944
6          Holly Springs, NC  35.654444  -78.824722
7             Ridgefield, CT  41.305278  -73.501389
8                Orlando, FL  28.540000  -81.380000
9                Kenosha, WI  42.582222  -87.845556
10    Green Cove Springs, FL  29.992778  -81.683889
11                Adrian, MI  41.896389  -84.037778
12          West Chicago, IL  41.888333  -88.209722
13             Kennewick, WA  46.203611 -119.159167
14             Rock Hill, SC  34.938056  -81.026111
15                 Minot, ND  48.233056 -101.292222
16                Norman, OK  35.220000   97.440000
17              Loveland, OH  39.268889  -84.270556
18          Pickerington, OH  39.892222  -82.763889
19            Logansport, IN  40.753611  -86.360556
20            Lake Villa, IL  42.417500  -88.082222
21             Bountiful, UT  40.879722 -111.871667
22                Elyria, OH  41.373333  -82.101667
23          Hopkinsville, KY  36.854722  -87.488889
24             Jonesboro, GA  33.524444  -84.354167
25        Winter Springs, FL  28.693333  -81.278889
26              Anderson, SC  34.514444  -82.648889
27             Massillon, OH  40.796667  -81.521389
28             Pawtucket, RI  41.875833  -71.376944
29             Lansdowne, PA  39.941389  -75.275278
...                      ...        ...         ...
1035          Middletown, CT  41.562222  -72.650833
1036              Tucson, AZ  32.221667 -110.926389
1037      Fredericksburg, VA  38.301806  -77.470833
1038            Chandler, AZ  33.300000 -111.833333
1039        Independence, KY  38.953611  -84.546944
1040           Iowa City, IA  41.660000   91.530000
1041          Twin Falls, ID  42.555556 -114.470833
1042              Hudson, NH  42.555556 -114.470833
1043               Bowie, MD  38.964722  -76.744444
1044            Hartford, CT  41.762500  -72.674167
1045            Hamilton, OH  39.399444  -84.561389
1046            Matthews, NC  35.116944  -80.716389
1047        Grand Island, NE  40.922222  -98.358056
1048          Palm Coast, FL  29.538056  -81.223333
1049       Oklahoma City, OK  35.482222  -97.535000
1050          Evansville, IN  37.977222  -87.550556
1051              Wausau, WI  44.950000  -89.633333
1052         Dawsonville, GA  34.416667  -84.116667
1053              Kokomo, IN  40.482222  -86.131667
1054            Honolulu, HI  21.300000 -157.816667
1055           Sheboygan, WI  43.750000  -87.725000
1056          Piscataway, NJ  40.545640   74.460817
1057               Cocoa, FL  28.369444  -80.743889
1058        Cartersville, GA  34.183333  -84.800000
1059          Chatsworth, GA  34.772222  -84.778889
1060          Grandville, MI  42.903889  -85.757500
1061         New Britain, CT  41.675000  -72.787222
1062          Northville, MI  42.433333  -83.483333
1063             Waltham, MA  42.372222  -71.211389
1064              Butler, PA  40.860556  -79.894722

[1065 rows x 3 columns]

In [339]:
towny.to_csv('towny_w_locs')

In [1]:
towny

NameError: name 'towny' is not defined